# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd2dd76c69fa7e602555e035c4d4c51ed814f7115d684e0c768b6956647de954a9ff2b26ccf4d7ae887110906ce1a3e33834052f8113ef07adcf411a6c35ebb7

test:
  secret_key_base: 9c1cc806f2c560a17942534909047b1dbfe59943a229b02647231cce5d9ff1fea9ca1fbc96c6c752f9d58e8aad15ab1a90accd2be247776ec2542138c4e7004f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
